version: "1.0.0"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=uzzal71
      - MONGO_INITDB_ROOT_PASSWORD=uzzal123
    volumes:
      - mongo-db:/data/db

  # Redis Server
  redis:
    image: redis:latest
    command: redis-server --requirepass beeda@202303

volumes:
  mongo-db:
