version: "1.0.0"
services:
  node-app:
    container_name: node-app-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - APP_ENV=development
      - MONGO_USER=uzzal71
      - MONGO_PASSWORD=uzzal123
      - MONGO_PORT=27017
      - SESSION_SECRET=secret

    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=uzzal71
      - MONGO_INITDB_ROOT_PASSWORD=uzzal123
