version: "1.0.0"
services:
  nginx:
    container_name: nginx-server
    image: nginx:stable-alpine

  node-app:
    container_name: node-app
    build: .
    image: node-app-image:latest
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    container_name: mongo-db-dev
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=uzzal71
      - MONGO_INITDB_ROOT_PASSWORD=uzzal123
    volumes:
      - mongo-db:/data/db

  # Redis Server
  redis:
    container_name: redis-db-dev
    image: redis:latest
    command: redis-server --requirepass beeda@202303

volumes:
  mongo-db:
