version: "1.0.0"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        APP_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - APP_ENV=development
      - MONGO_USER=uzzal71
      - MONGO_PASSWORD=uzzal123
      - SESSION_SECRET=secret

    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=uzzal71
      - MONGO_INITDB_ROOT_PASSWORD=uzzal123
