version: "1.0.0"
services:
  node-app:
    container_name: node-app-prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: production
    environment:
      - APP_ENV=production
      - PORT=3000
    command: npm start
