version: "1.0.0"
services:
  node-app:
    container_name: node-app-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - APP_ENV=development
      - PORT=3000
    command: npm run dev
