version: "1.0.0"
services:
  nginx:
    ports:
      - "80:80"

  node-app:
    container_name: node-app-prod
    build:
      context: .
      args:
        APP_ENV: production
    environment:
      - APP_ENV=production
    command: npm start
