version: "1.0.0"
services:
  node-app-dev:
    build:
      context: .
      args:
        APP_ENV: development
    environment:
      - port=3000
      - APP_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules

    command: npm run dev
