version: "3"
services:
  node-app:
    container_name: node-app
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3000

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=uzzal71
      - MONGO_INITDB_ROOT_PASSWORD=uzzal@123
