version: "3"
services:
  node-app:
    container_name: node-app
    build: .
    image: node-app-image:latest
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    # env_file:
    #   - ./.env
